export default {

   // BÁSICOS
   no: "❌",
   yes: "✅",
   loading: "⏳",
   flechader: "➡️",
   flechaizq: "⬅️",
   flechaderlong: "▶️",
   flechaizqlong: "◀️",
   doubleflechader: "⏭️",
   doubleflechaizq: "⏮️",
   flechalonger: "🔀",
   flechalongerder: "🔁",
   joined: "📥",
   left: "📤",
   disk: "💿",
   builder: "🔧",
   escudo: "🛡️",
   role: "🎭",
   discord: "💬",
   bot: "🤖",
   userlimit: "👥",
   niby: "🎯",
   like: "👍",
   thread: "🧵",
   channel: "📺",
   warn: "⚠️",
   alert: "🚨",
   escudo2: "🛡️",
   money: "💰",
   boost: "🚀",
   info: "ℹ️",
   clock: "⌚",
   crown: "👑",
   gear: "⚙️",
   nsfw: "🔞",
   question: "❓",
   command: "⌨️",
   wifi: "📶",
   giveaway: "🎉",
   controller: "🎮",
   mouse: "🖱️",
   muscle: "💪",

   // BADGES,
   HypeSquadOnlineHouse3: "⚖️",
   HypeSquadOnlineHouse2: "🔥",
   HypeSquadOnlineHouse1: "⚡",
   ActiveDeveloper: "👨‍💻",

   // ESTADOS DE USUARIO
   online: "🟢",
   offline: "⚪",
   idle: "🟡",
   dnd: "🔴",

   // REDES SOCIALES
   youtube: "📺",
   twitter: "🐦",
   twitch: "🎮",
   spotify: "🎵",
   soundcloud: "☁️",
   deezer: "🎧",
   paypal: "💳",
   patreon: "🎨",
   github: "🐙",

   dewstouh: "⭐",


   favourite: "⭐",
   wait: "⏰",
   person: "👤",
   link: "🔗",
   chat: "💬",
   pc: "💻",
   lupa: "🔍",


   // EMOJIS DE MÚSICA
   notes: "🎵",
   volume: "🔊",
   stop: "⏹️",
   skip: "⏭️",
   backward: "⏮️",
   forward: "⏩",
   pause: "⏸️",
   resume: "▶️",
   loop: "🔁",
   autoplay: "🔀",
   mic: "🎤",
   gem: "💎",
   coin: "🪙",
   load: "📁"
}
